# Generated by Django 4.1.3 on 2023-01-17 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('personId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('IdentityNumber', models.CharField(db_column='IdentityNumber', max_length=13)),
                ('FirstName', models.CharField(db_column='FirstName', max_length=50)),
                ('Middlename', models.CharField(db_column='MiddleName', max_length=50)),
                ('lastname', models.CharField(db_column='Lastname', max_length=50)),
                ('altcellphone', models.CharField(db_column='AltCellPhone', max_length=20)),
                ('altemail', models.CharField(db_column='AltEmail', max_length=50)),
                ('physicaladdress1', models.CharField(db_column='PhysicalAddress1', max_length=100)),
                ('physicaladdress2', models.CharField(db_column='PhysicalAddress2', max_length=100)),
                ('shoesize', models.IntegerField(blank=True, db_column='ShoeSize', null=True)),
                ('tracksuitsize', models.IntegerField(blank=True, db_column='TrackSuitSize', null=True)),
                ('disability', models.CharField(db_column='Disability', max_length=100)),
                ('disabilitydescription', models.CharField(db_column='DisabilityDescription', max_length=300)),
                ('gender', models.CharField(db_column='Gender', max_length=20)),
                ('ethnicity', models.CharField(db_column='Ethnicity', max_length=50)),
                ('cellphone', models.CharField(db_column='Cellphone', max_length=20)),
                ('NumProfile', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Nextofkin',
            fields=[
                ('ID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Title', models.CharField(db_column='Title', max_length=100)),
                ('FirstName', models.CharField(db_column='FirstName', max_length=100)),
                ('Surname', models.CharField(db_column='Surname', max_length=100)),
                ('Relationship', models.CharField(db_column='Relationship', max_length=100)),
                ('Jobtitle', models.CharField(db_column='JobTitle', max_length=100)),
                ('JobDescription', models.CharField(db_column='JobDescription', max_length=100)),
                ('HomeAddress', models.CharField(db_column='HomeAddress', max_length=100)),
                ('WorkAddress', models.CharField(db_column='WorkAddress', max_length=100)),
                ('EmailAddress', models.CharField(db_column='EmailAddress', max_length=100)),
                ('PhoneNumber', models.CharField(db_column='PhoneNumber', max_length=20)),
                ('Gender', models.CharField(db_column='Gender', max_length=20)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
            options={
                'db_table': 'NextOfKin',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('Employment_id', models.AutoField(db_column='Employment_ID', primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(db_column='CompanyName', max_length=100)),
                ('CompanyAddress', models.CharField(db_column='CompanyAddress', max_length=100)),
                ('CurrentlyWorking', models.BooleanField(db_column='CurrentlyWorking', default=False)),
                ('Telephone', models.CharField(db_column='Telephone', max_length=20)),
                ('WorkPosition', models.CharField(db_column='WorkPosition', max_length=100)),
                ('StartDate', models.DateField(blank=True, db_column='StartDate', null=True)),
                ('EndDate', models.DateField(blank=True, db_column='EndDate', null=True)),
                ('Skills', models.CharField(db_column='SKills', max_length=100)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
            options={
                'db_table': 'Employment',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('education_id', models.AutoField(db_column='Education_Id', primary_key=True, serialize=False)),
                ('EducationLevel', models.CharField(db_column='EducationLevel', max_length=50)),
                ('SchoolAddress', models.CharField(db_column='SchoolAddress', max_length=50)),
                ('YearStarted', models.DateField(blank=True, db_column='YearStarted', null=True)),
                ('YearEnd', models.DateField(blank=True, db_column='YearEnd', null=True)),
                ('Completed', models.BooleanField(db_column='Completed', default=False)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
            options={
                'db_table': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Doctorsinformation',
            fields=[
                ('DoctorsId', models.AutoField(db_column='DoctorsId', primary_key=True, serialize=False)),
                ('FirstName', models.CharField(db_column='FirstName', max_length=50)),
                ('Surname', models.CharField(db_column='Surname', max_length=50)),
                ('Speciality', models.CharField(db_column='Speciality', max_length=50)),
                ('Role', models.CharField(db_column='Role', max_length=50)),
                ('CellNumber', models.IntegerField(blank=True, db_column='CellNumber', null=True)),
                ('EmailAddress', models.CharField(db_column='EmailAddress', max_length=50)),
                ('WorkAddress', models.CharField(db_column='WorkAddress', max_length=50)),
                ('WorkTel', models.IntegerField(blank=True, db_column='WorkTel', null=True)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
            options={
                'db_table': 'DoctorsInformation',
            },
        ),
    ]
