# Generated by Django 4.1.3 on 2023-01-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagePersonal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='personId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
