# Generated by Django 4.1.3 on 2023-01-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ManagePersonal', '0002_alter_persons_personid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('FeildId', models.AutoField(db_column='FeildId', primary_key=True, serialize=False)),
                ('FeildName', models.CharField(db_column='FeildName', max_length=50)),
                ('FeildValue', models.TextField(db_column='FeildValue')),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
        ),
    ]
