# Generated by Django 4.1.3 on 2023-01-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagePersonal', '0003_customfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='FeildValue',
            field=models.TextField(db_column='FeildValue', max_length=100),
        ),
        migrations.AlterModelTable(
            name='customfield',
            table='CustomField',
        ),
    ]
