# Generated by Django 4.1.3 on 2023-01-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagePersonal', '0004_alter_customfield_feildvalue_alter_customfield_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='HighestGrade',
            field=models.CharField(db_column='HighestGrade', default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='InstitutionName',
            field=models.CharField(default='Unknown school', max_length=70),
        ),
        migrations.AlterField(
            model_name='persons',
            name='tracksuitsize',
            field=models.CharField(blank=True, db_column='TrackSuitSize', max_length=50, null=True),
        ),
    ]
