# Generated by Django 4.1.3 on 2023-01-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ManagePersonal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('ParentId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='manageProfile/images')),
                ('JoinDate', models.DateTimeField()),
                ('Default', models.BooleanField(default=False)),
                ('Status', models.CharField(default='Active', max_length=50)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
            options={
                'db_table': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('OfficialID', models.AutoField(auto_created=True, db_column='OfficialID', primary_key=True, serialize=False)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='manageProfile/images')),
                ('Position', models.TextField(max_length=50)),
                ('JoinDate', models.DateTimeField()),
                ('Default', models.BooleanField(default=False)),
                ('Status', models.CharField(default='Active', max_length=50)),
                ('Federation', models.TextField(max_length=50)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
            options={
                'db_table': 'Official',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('CoachID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='manageProfile/images')),
                ('CoachLevel', models.CharField(max_length=50)),
                ('Status', models.CharField(default='Active', max_length=50)),
                ('Default', models.BooleanField(default=False)),
                ('JoinDate', models.DateTimeField()),
                ('Federation', models.TextField(max_length=50)),
                ('ClubName', models.TextField(max_length=50)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
            options={
                'db_table': 'Coach',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('AthleteID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='manageProfile/images')),
                ('Federation', models.TextField(max_length=50)),
                ('PlayerType', models.TextField(max_length=50)),
                ('AthleteLevel', models.CharField(max_length=50)),
                ('ClubName', models.TextField(max_length=50)),
                ('ClubLevel', models.CharField(max_length=50)),
                ('JoinDate', models.DateTimeField()),
                ('Default', models.BooleanField(default=False)),
                ('Status', models.CharField(default='Active', max_length=50)),
                ('ParentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageProfile.parent')),
                ('personId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ManagePersonal.persons')),
            ],
            options={
                'db_table': 'Athlete',
            },
        ),
    ]
