# Generated by Django 4.1.3 on 2023-01-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('AchievementId', models.AutoField(db_column='AchievementId', primary_key=True, serialize=False)),
                ('TypeOfAchievement', models.CharField(db_column='TypeOfAchievement', max_length=50)),
                ('nNameOfAchievement', models.CharField(db_column='NameOfAchievement', max_length=50)),
                ('Organization', models.CharField(db_column='Organization', max_length=50)),
                ('YearOfAchievement', models.DateField(blank=True, db_column='YearOfAchievement', null=True)),
                ('Certificate', models.CharField(db_column='Certificate', max_length=50)),
                ('ExecutiveID', models.IntegerField(blank=True, db_column='ExexutiveID', null=True)),
                ('AthleteID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageProfile.athlete')),
                ('CoachID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageProfile.coach')),
                ('OfficialID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageProfile.official')),
            ],
            options={
                'db_table': 'Achievements',
            },
        ),
    ]
