# Generated by Django 4.1.3 on 2023-01-01 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='personId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageProfile.persons'),
        ),
    ]
