# Generated by Django 4.1.3 on 2022-12-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Default',
            field=models.BooleanField(default=False),
        ),
    ]
