# Generated by Django 4.1.3 on 2023-01-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0002_alter_athlete_personid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('OfficialID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ProfileImage', models.ImageField(blank=True, null=True, upload_to='manageProfile/images')),
                ('Position', models.TextField(max_length=50)),
                ('JoinDate', models.DateTimeField()),
                ('Default', models.BooleanField(default=False)),
                ('Status', models.CharField(default='Active', max_length=50)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageProfile.persons')),
            ],
        ),
    ]
