# Generated by Django 4.1.3 on 2022-12-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0002_alter_athlete_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='ProfileImage',
            field=models.ImageField(upload_to='manageProfile/images'),
        ),
    ]
