# Generated by Django 4.1.3 on 2022-12-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0002_parent_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='Status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
