# Generated by Django 4.1.3 on 2023-01-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0003_rename_nnameofachievement_achievements_nameofachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='ExecutiveID',
        ),
    ]
