# Generated by Django 4.1.3 on 2023-01-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0003_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='Federation',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
