# Generated by Django 4.1.3 on 2022-12-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0003_alter_athlete_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='Default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persons',
            name='NumProfile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='manageProfile/images'),
        ),
    ]
