# Generated by Django 4.1.3 on 2022-12-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0004_athlete_default_persons_numprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='Status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
