# Generated by Django 4.1.3 on 2023-01-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageProfile', '0005_rename_achievements_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='YearOfAchievement',
            field=models.DateField(blank=True, db_column='YearOfAchievement', default='<jamming-date>', null=True),
        ),
    ]
